# Ruff configuration
line-length = 100
indent-width = 4
fix = true
unsafe-fixes = false

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[lint]
select = [
	"E",   # pycodestyle
	"F",   # pyflakes
	"I",   # isort
	"UP",  # pyupgrade
	"B",   # bugbear
	"W",   # warnings (pycodestyle)
	"C90", # mccabe complexity
	"N",   # pep8-naming
	"RUF", # Ruff specific
]
ignore = [
	"E501", # line length handled by formatter
]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[lint.per-file-ignores]
"bot/__init__.py" = ["F401"]
"bot/version.py" = ["F401"]